name: fyp_assist
description: A mobile-first project management app for Pakistani university students.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  firebase_storage: ^11.6.9
  firebase_messaging: ^14.7.19  # NEW: For Push Notifications

  # State Management
  flutter_riverpod: ^2.5.1
  
  # File Services
  file_picker: ^8.0.0+1
  url_launcher: ^6.3.0

  # Notifications UI
  flutter_local_notifications: ^17.2.2

  # Other useful packages
  intl: ^0.19.0 

  cupertino_icons: ^1.0.2

  # Additional packages for advanced features
  flutter_slidable: ^3.0.1
  cached_network_image: ^3.3.1
  flutter_staggered_animations: ^1.1.1
  table_calendar: ^3.0.9
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3

  # New features
  webview_flutter: ^4.4.2
  googleapis: ^11.4.0
  google_sign_in: ^6.2.1
  pdf: ^3.10.7
  csv: ^6.0.0
  github: ^9.24.0
  http: ^1.2.1
  share_plus: ^7.2.2
  webview_flutter_web: ^0.2.3+4

flutter:
  uses-material-design: true
  assets:
    - assets/images/